### ISSUE TITLE
dead code: getDisclosureButton 

### ISSUE THREAD

**Issue by christopherallanperry** [tabvengers/spicy-sections#20]
When browsing the JS file, I noticed the function getDisclosureButton(). It's unreferenced in either the JS file itself or, the demo HTML, nor can I find mention of it anywhere else around `<spicy-sections>`.  Can I ask where it fits in the overall scheme of things?

**Comment by bkardell** [comment]
It is currently dead code, we'll remove it... There were two versions of this, one which also projected a button in the collapse forms, and this was used to access it.  There's much to debate and up in the air, so we chose to bring this conceptually to developers and start getting feedback and thoughts rather than waffle on a few different implementation ideas.

**Comment by bkardell** [comment]
closed by #28
